### ISSUE TITLE
calculate fungal abundance within metagenomic samples

### ISSUE THREAD

**Issue by MonaLiu421** [yexianingyue/Cultivated-Gut-Fungi#1]
Hello, I hope this message finds you well. I would like to know more about the methodology or process you used to identify species-specific genes and shared genes. Furthermore, I am particularly interested in understanding how you aligned the sequencing reads to these identified genes and performed the subsequent counting. Any details you could provide regarding the alignment and counting steps would be greatly appreciated.

Thank you for your time and consideration. I look forward to hearing from you.

Best regards,
Mona

**Comment by yexianingyue** [comment]
Hello,

I apologize for the delay in getting back to you.

The latest commit version of the [README](../tree/main/Fungi_profile_algo/example/README.md) provides a detailed introduction. The updated [example](../tree/main/Fungi_profile_algo/example/) can be run directly and includes specific commands. I hope this update addresses your concerns. If you have any further questions, feel free to reach out to me.

Best regards,  
Yexia
